apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/managed-by: Kustomize
resources:
  - ./metallb/pool.yaml
  - ./cert-manager/cluster-issuer.yaml
  - ./cert-manager/issuer.yaml
  - ./rook-ceph/dashboard-external-https.yaml
  - ./rook-ceph/dashboard-ingress-https.yaml
