---
compatWithCPUManager: true
resources:
  requests:
    cpu: 100m
  limits:
    memory: 512Mi
nvidiaDriverRoot: /run/current-system/sw/
gfd:
  enabled: true
nodeSelector:
  kubernetes.io/hostname: homelab01


config:
   map:
     default: |-
       version: v1
       flags:
         migStrategy: none
     mig-single: |-
       version: v1
       flags:
         migStrategy: single
     mig-mixed: |-
       version: v1
       flags:
         migStrategy: mixed
