registry: noop
provider: pihole
pihole:
  server: http://pihole-web.pihole-system.svc.cluster.local
  tlsSkipVerify: true
policy: upsert-only
serviceAccount:
  create: true
  name: "external-dns"
sources:
  - service
  - ingress
ingressClassFilters:
  - nginx-internal
txtOwnerId: "homelab"
extraEnvVars:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: password
