---
DNS1:
  192.168.1.1
persistentVolumeClaim:
  enabled: true
ingress:
  enabled: true
  hosts:
    - "pihole.home"
serviceWeb:
  loadBalancerIP: 192.168.1.250
  labels:
    ip-addr: "true"
  type: LoadBalancer
servicedns:
  loadBalancerIP: 192.168.1.250
  labels:
    ip-addr: "true"
  type: LoadBalancer
replicaCount: 1
