deploymentMode: SingleBinary
loki:
  auth_enabled: false
  querier:
    multi_tenant_queries_enabled: false
  enableServiceLinks: true
  configStorageType: Secret
  pattern_ingester:
    enabled: true
  limits_config:
    ingestion_rate_strategy: local
    ingestion_rate_mb: 10000
    ingestion_burst_size_mb: 1000
    max_label_name_length: 10240
    retention_period: 24h
    reject_old_samples: false
    max_cache_freshness_per_query: 10m
    split_queries_by_interval: 15m
    per_stream_rate_limit: 512M
    per_stream_rate_limit_burst: 1024M
    cardinality_limit: 200000
    max_entries_limit_per_query: 1000000
    max_label_value_length: 20480
    max_label_names_per_series: 300
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: filesystem
      schema: v13
singleBinary:
  replicas: 1
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
