auth:
  # This is the necessary configuration you will need for the Installer, minus the hostname
  database: "synapse"
  username: "synapse"
  existingSecret: "postgresql-secret"
  secretKeys:
    adminPasswordKey: "postgres-password"
    userPasswordKey: "password"
    replicationPasswordKey: "replication-password"
  usePasswordFiles: false
primary:
  initdb:
    args: "--lc-collate=C --lc-ctype=C"
  persistence:
    enabled: true
    size: 20Gi
