#!/usr/bin/env fish

terraform import module.element.kubernetes_namespace.element element
terraform import module.element.helm_release.element_web element/element-web
terraform import module.ingress.module.internal_ingress.kubernetes_namespace.nginx internal-nginx-system
terraform import module.ingress.module.internal_ingress.helm_release.ingress_nginx internal-nginx-system/ingress-nginx-internal
terraform import module.ingress.module.external_ingress.kubernetes_namespace.nginx nginx-system
terraform import module.ingress.module.external_ingress.helm_release.ingress_nginx nginx-system/ingress-nginx
terraform import module.ingress.kubernetes_namespace.cert_manager cert-manager
terraform import module.ingress.helm_release.cert_manager cert-manager/cert-manager
terraform import module.ingress.kubernetes_manifest.cluster_issuer "apiVersion=cert-manager.io/v1,kind=ClusterIssuer,namespace=cert-manager,name=letsencrypt-prod"
terraform import module.matrix.kubernetes_namespace.matrix matrix
terraform import module.matrix.kubernetes_persistent_volume_claim.matrix_media matrix/matrix-media-repo
terraform import module.matrix.helm_release.matrix_media_repo matrix/matrix-media-repo
terraform import module.matrix.helm_release.matrix_synapse matrix/matrix-synapse
terraform import module.matrix.kubernetes_manifest.matrix_podmonitor "apiVersion=monitoring.coreos.com/v1,kind=PodMonitor,name=matrix-synapse,namespace=matrix"
terraform import module.matrix.kubernetes_manifest.prometheus_matrix_rules "apiVersion=monitoring.coreos.com/v1,kind=PrometheusRule,name=prometheus-matrix-rules,namespace=matrix"
terraform import module.metallb.kubernetes_namespace.metallb metallb-system
terraform import module.metallb.resource.helm_release.metallb metallb-system/metallb
terraform import module.metallb.kubernetes_manifest.ip_pool "apiVersion=metallb.io/v1beta1,kind=IPAddressPool,name=pool,namespace=metallb-system"
terraform import module.metallb.kubernetes_manifest.ip_advertisement "apiVersion=metallb.io/v1beta1,kind=L2Advertisement,name=pool,namespace=metallb-system"
terraform import module.monitoring.kubernetes_namespace.monitoring monitoring
terraform import module.monitoring.resource.kubernetes_secret.grafana_admin_credentials monitoring/grafana-admin-credentials
terraform import module.monitoring.resource.kubernetes_role.grafana monitoring/grafana-secret
terraform import module.monitoring.kubernetes_role_binding.grafana monitoring/grafana-secrets
terraform import module.monitoring.resource.helm_release.prometheus_stack monitoring/prometheus-stack
terraform import module.monitoring.resource.helm_release.alloy monitoring/alloy
terraform import module.monitoring.resource.helm_release.loki monitoring/loki
terraform import module.monitoring.kubernetes_ingress_v1.grafana_external monitoring/grafana-external
terraform import module.pihole.kubernetes_namespace.pihole pihole-system
terraform import module.pihole.helm_release.pihole pihole-system/pihole
terraform import module.pihole.helm_release.externaldns_pihole pihole-system/externaldns-pihole
terraform import module.postgresql.kubernetes_namespace.postgresql postgresql
terraform import module.postgresql.kubernetes_secret.postgresql postgresql/postgresql-secret
terraform import module.postgresql.helm_release.postgresql postgresql/postgresql
terraform import module.rook_ceph.kubernetes_namespace.rook_ceph rook-ceph
terraform import module.rook_ceph.helm_release.rook_ceph rook-ceph/rook-ceph
terraform import module.rook_ceph.helm_release.rook_ceph_cluster rook-ceph/rook-ceph-cluster
terraform import module.rook_ceph.kubernetes_manifest.csi_metrics "apiVersion=monitoring.coreos.com/v1,kind=ServiceMonitor,name=csi-metrics,namespace=rook-ceph"
terraform import module.rook_ceph.kubernetes_service.ceph_dashboard rook-ceph/rook-ceph-mgr-dashboard-external-https
terraform import module.rook_ceph.kubernetes_ingress_v1.ceph_dashboard rook-ceph/rook-ceph-mgr-dashboard
terraform import module.rook_ceph.kubernetes_manifest.ceph_prometheus_rules "apiVersion=monitoring.coreos.com/v1,kind=PrometheusRule,name=prometheus-ceph-external-rules,namespace=rook-ceph"
terraform import module.rook_ceph.kubernetes_manifest.prometheusrule_rook_ceph_prometheus_ceph_rules "apiVersion=monitoring.coreos.com/v1,kind=PrometheusRule,name=prometheus-ceph-rules,namespace=rook-ceph"
