apiVersion: v1
kind: ConfigMap
metadata:
  name: "postgres-init-scripts"
  namespace: postgresql
data:
  create_uesrs.sh: |
    #!/bin/sh
    psql << E_O_SQL
    CREATE USER matrix_media_repo WITH NOSUPERUSER CREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:UwcncrQheM0He/hJOOVb5Q==$K5DGxT+4tzW0Jj9Hi/nXIrNM+RfBPLD6c+T/3eiKaMo=:3/nH4Tbt/SrKEY7id0ato7s0LtT+qWeAqDMoHH5w8lA=';
    CREATE DATABASE matrix_media_repo WITH OWNER = 'matrix_media_repo';
    E_O_SQL
