apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus
    role: alert-rules
  name: prometheus-matrix-rules
  namespace: matrix
spec:
  groups:
    - name: synapse
      rules:
        - record: 'synapse_federation_client_sent'
          labels:
            type: "EDU"
          expr: 'synapse_federation_client_sent_edus_total + 0'
        - record: 'synapse_federation_client_sent'
          labels:
            type: "PDU"
          expr: 'synapse_federation_client_sent_pdu_destinations_count_total + 0'
        - record: 'synapse_federation_client_sent'
          labels:
            type: "Query"
          expr: 'sum(synapse_federation_client_sent_queries) by (job)'

        - record: 'synapse_federation_server_received'
          labels:
            type: "EDU"
          expr: 'synapse_federation_server_received_edus_total + 0'
        - record: 'synapse_federation_server_received'
          labels:
            type: "PDU"
          expr: 'synapse_federation_server_received_pdus_total + 0'
        - record: 'synapse_federation_server_received'
          labels:
            type: "Query"
          expr: 'sum(synapse_federation_server_received_queries) by (job)'

        - record: 'synapse_federation_transaction_queue_pending'
          labels:
            type: "EDU"
          expr: 'synapse_federation_transaction_queue_pending_edus + 0'
        - record: 'synapse_federation_transaction_queue_pending'
          labels:
            type: "PDU"
          expr: 'synapse_federation_transaction_queue_pending_pdus + 0'
        
        - record: synapse_storage_events_persisted_by_source_type
          expr: sum without(type, origin_type, origin_entity) (synapse_storage_events_persisted_events_sep_total{origin_type="remote"})
          labels:
            type: remote
        - record: synapse_storage_events_persisted_by_source_type
          expr: sum without(type, origin_type, origin_entity) (synapse_storage_events_persisted_events_sep_total{origin_entity="*client*",origin_type="local"})
          labels:
            type: local
        - record: synapse_storage_events_persisted_by_source_type
          expr: sum without(type, origin_type, origin_entity) (synapse_storage_events_persisted_events_sep_total{origin_entity!="*client*",origin_type="local"})
          labels:
            type: bridges

        - record: synapse_storage_events_persisted_by_event_type
          expr: sum without(origin_entity, origin_type) (synapse_storage_events_persisted_events_sep_total)

        - record: synapse_storage_events_persisted_by_origin
          expr: sum without(type) (synapse_storage_events_persisted_events_sep_total)
