---
replicaCount: 1
image:
  repository: vectorim/element-web
  pullPolicy: IfNotPresent

imagePullSecrets: []

## Default server for the Element install. (Required)
## This will configure the default_server_config block in the config.json
## Ref: https://github.com/vector-im/element-web/blob/develop/config.sample.json
##
defaultServer:
  url: 'https://matrix.jpeg.gay'
  name: 'jpeg.gay'
  identity_url: 'https://vector.im'

## Element configuration
## Ref: https://github.com/vector-im/element-web/blob/develop/config.sample.json
##
config:
  default_server_name: jpeg.gay
  brand: Element
  integrations_ui_url: 'https://scalar.vector.im/'
  integrations_rest_url: 'https://scalar.vector.im/api'
  integrations_widgets_urls:
    - 'https://scalar.vector.im/_matrix/integrations/v1'
    - 'https://scalar.vector.im/api'
    - 'https://scalar-staging.vector.im/_matrix/integrations/v1'
    - 'https://scalar-staging.vector.im/api'
    - 'https://scalar-staging.riot.im/scalar/api'
  bug_report_endpoint_url: 'https://element.io/bugreports/submit'
  uisi_autorageshake_app: element-auto-uisi
  show_labs_settings: true
  room_directory:
    servers:
      - jepg.gay
      - matrix.org
      - gitter.im
  enable_presence_by_hs_url:
    'https://jpeg.gay': true
    'https://matrix.jpeg.gay': true
    'https://matrix.org': false
    'https://matrix-client.matrix.org': false
  terms_and_conditions_links:
    - url: 'https://element.io/privacy'
      text: Privacy Policy
    - url: 'https://element.io/cookie-policy'
      text: Cookie Policy
  privacy_policy_url: 'https://element.io/cookie-policy'
  map_style_url: 'https://api.maptiler.com/maps/streets/style.json?key=Lztor3PhA9a7A5ygJlsE'
  setting_defaults:
    RustCrypto.staged_rollout_percent: 60


## Configuration to add into the nginx server object
##
nginxConfig: |-
  add_header X-Frame-Options SAMEORIGIN;
  add_header X-Content-Type-Options nosniff;
  add_header X-XSS-Protection "1; mode=block";
  add_header Content-Security-Policy "frame-ancestors 'self'";

## Configuration for mounting additional volumes into the application container.
##
extraVolumes: {}
  #  - name: element
  #    persistentVolumeClaim:
  #      claimName: element
extraVolumeMounts: {}
  #  - name: element
  #    mountPath: /app/themes/element/img/backgrounds/

## Configures an application-specific service account.
##
serviceAccount:
  create: false

  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  # name: ""

## Additional annotations to add to the pod.
##
podAnnotations: {}

## Security context configuration to add to the pod.
##
podSecurityContext: {}
  #  fsGroup: 2000

## Security context configuration to add to the container inside the pod.
##
securityContext: {}
  #  capabilities:
  #    drop:
  #    - ALL
  #  readOnlyRootFilesystem: false
  #  runAsNonRoot: true
  #  runAsUser: 1000

## Service configuration.
##
service:
  type: LoadBalancer
  port: 80

## Ingress configuration.
##
ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

  hosts:
    - chat.jpeg.gay
  tls:
    - secretName: chat.jpeg.gay
      hosts:
        - chat.jpeg.gay 

  ## Set the name of the IngressClass cluster resource (optional)
  ## https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec

## Resource configuration for the application.
##
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Configure auto-scaling for the application.
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

## Node selectors to use when deploying the application.
##
nodeSelector: {}

## Tolerations to apply to the application.
##
tolerations: []

## Affinities to set on the application.
##
affinity: {}
