repositories:
  - name: rook-release
    url: https://charts.rook.io/release

  - name: metallb
    url: https://metallb.github.io/metallb

  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/

  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: jetstack
    url: https://charts.jetstack.io

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: ananace-charts
    url: https://ananace.gitlab.io/charts

---
releases:
  # Distributed storage
  - name: rook-ceph
    namespace: rook-ceph
    chart: rook-release/rook-ceph
    version: 1.14.9
    values:
      - ./values/rook-ceph.values.yaml

  - name: rook-ceph-cluster
    namespace: rook-ceph
    chart: rook-release/rook-ceph-cluster
    version: 1.14.9
    values:
      - ./values/rook-ceph-cluster.values.yaml

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.8

  # pihole
  - name: pihole
    namespace: pihole-system
    chart: mojo2600/pihole
    version: 2.26.1
    values:
      - ./values/pihole.values.yaml

  # Ingress for local network
  - name: ingress-nginx-internal
    namespace: internal-nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.1
    values:
      - ./values/nginx-internal.values.yaml

  # Ingress for local network
  - name: ingress-nginx
    namespace: nginx-system
    chart: ingress-nginx/ingress-nginx
    version: 4.11.1
    values:
      - ./values/nginx.values.yaml

  # Automatic DNS for pihole
  - name: externaldns-pihole
    namespace: pihole-system
    chart: bitnami/external-dns
    version: 8.3.3
    values:
      - ./values/externaldns.values.yaml

  # Enable cluster wide certificates
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: 1.15.1
    values:
      - ./values/cert-manager.values.yaml

  # Setup full monitoring stack
  - name: prometheus-stack
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 61.6.0
    values:
      - ./values/prometheus-stack.values.yaml

    # Postgresql
  - name: postgresql
    namespace: postgresql
    chart: bitnami/postgresql
    version: 15.5.20
    values:
      - ./values/postgresql.values.yaml

  # Element Web client
  - name: element-web
    namespace: element
    chart: ananace-charts/element-web
    version: 1.3.28
    values:
      - ./values/element-web.values.yaml

  # Matrix media
  - name: matrix-media-repo
    namespace: matrix
    chart: ananace-charts/matrix-media-repo
    version: 3.0.6
    values:
      - ./values/matrix-media-repo.values.yaml

  # Matrix federation server
  - name: matrix-synapse
    namespace: matrix
    chart: ananace-charts/matrix-synapse
    version: 3.9.9
    values:
      - ./values/matrix-synapse.values.yaml
